name: Test status checks
on:
  push:
    tags:
      - "*"

jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit status
        run: |
          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_SHA}

          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CI_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/status
