name: Test status checks
on:
  push:
    tags:
      - "*"

jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit status
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer <YOUR-TOKEN>" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/commits/GITHUB_SHA/status
